### ISSUE TITLE
Metrics API returns floating point values

### ISSUE THREAD

**Issue by shinya-terasaki** [stoiveyp/Alexa.NET.Management#62]
Hello,

Thank you for implementing Metrics API.

I tested, but it generated following exception.

```
  Expected: No Exception to be thrown
  But was:  <Newtonsoft.Json.JsonReaderException: Input string '3.0' is not a valid integer. Path 'values[0]', line 1, position 608.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Refit.JsonContentSerializer.DeserializeAsync[T](HttpContent content) in d:\a\1\s\Refit\JsonContentSerializer.cs:line 45
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext()
```

Actually the response contains floating point values.
```
{"metric":"uniqueCustomers","timestamps":["2019-11-04T00:00:00Z","2019-11-04T01:00:00Z","2019-11-04T02:00:00Z","2019-11-04T03:00:00Z","2019-11-04T04:00:00Z","2019-11-04T05:00:00Z","2019-11-04T06:00:00Z","2019-11-04T07:00:00Z","2019-11-04T08:00:00Z","2019-11-04T09:00:00Z","2019-11-04T10:00:00Z","2019-11-04T11:00:00Z","2019-11-04T12:00:00Z","2019-11-04T13:00:00Z","2019-11-04T14:00:00Z","2019-11-04T15:00:00Z","2019-11-04T16:00:00Z","2019-11-04T17:00:00Z","2019-11-04T18:00:00Z","2019-11-04T19:00:00Z","2019-11-04T20:00:00Z","2019-11-04T21:00:00Z","2019-11-04T22:00:00Z","2019-11-04T23:00:00Z"],"values":[3.0,6.0,5.0,2.0,3.0,7.0,3.0,5.0,5.0,14.0,10.0,4.0,5.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0]}
```

`MetricsResponse` expects integer for values, but it should be float/double.

BR,

**Comment by stoiveyp** [comment]
Thank you for raising this @shinya-terasaki - this has now been corrected in v3.8.1 👍
